# Generated by Django 4.2.2 on 2023-07-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_picture',
            new_name='image',
        ),
    ]
