# Generated by Django 4.2.2 on 2023-07-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_getintouch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getintouch',
            name='body',
        ),
        migrations.AddField(
            model_name='getintouch',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
